[sc-107224] prepare release
dataiku/dss-plugin-eks-clusters pull request #39
Opened 2022-11-07 13:56 UTC by amandineslx

2022-11-08 07:58 UTC, jules-casoli requested changes

2022-11-08 07:58 UTC, jules-casoli commented on CHANGELOG.md
> +## Version 1.0.10 - Feature release
```suggestion
## Version 1.0.10 - Bugfix release
```
?

2022-11-08 09:14 UTC, jules-casoli commented on CHANGELOG.md
> +## Version 1.0.10 - Feature release
ha, indeed, Fred forgot to update the Changelog.

2022-11-08 09:14 UTC, jules-casoli approved these changes

2022-11-09 15:41 UTC, thtrunck approved these changes
LGTM

2022-11-09 17:15 UTC, merged