EKS parse no integer in kubectl version
dataiku/dss-plugin-eks-clusters pull request #50
Opened 2023-06-02 08:34 UTC by amandineslx

`kubectl` version provided by Amazon has a minor version finishing by '+'

this minor version is used in a comparison in a condition to decide which version of the AWS authenticator should be used

keeping only the first numeric section to consider as the minor version

2023-06-02 13:56 UTC, FChataigner requested changes

2023-06-02 13:56 UTC, FChataigner commented on python-lib/dku_utils/tools_version.py
> +    if len(search_results_minor_int.groups()) < 1:
you need to check `search_results_minor_int is not None` too (ie the case where there is no match at all)

2023-06-02 13:56 UTC, FChataigner commented on python-lib/dku_utils/tools_version.py
> +    regex_minor_int = re.compile("^[^0-9]*([0-9]+)")
for the sake of nitpicking, I'd require a 2-digits minor with `[0-9]{2,}` (unless we expect a 2.0 of kubectl soon), or being more explicit with the greediness and do something like `^[^0-9]*([0-9]+)([^0-9].*$|$)`

2023-06-05 12:04 UTC, marchelleboid approved these changes
Tested with versions `1.23` and `1.24+` and it worked for creation and attach.

2023-06-05 13:47 UTC, FChataigner approved these changes

2023-06-13 07:54 UTC, merged